class DefaultKeywords {
  static Map<String, List<String>> keywords = {
    "Girlfriend": [
      'chocolate',
      'flowers',
      'garden',
      'kitchen',
      'home',
      'decorations',
      'wine',
      'basket',
      'cookbook',
      'soap',
      'candel',
      'picture',
      'earrings',
      'necklace',
    ],
    "Boyfriend": [
      'bbq',
      'outdoors',
      'fishing',
      'hunting',
      'sports',
      'football',
      'hockey',
      'basketball',
      'video',
      'game',
      'xbox',
      'PS4',
    ],
    "Father": [
      'bbq',
      'outdoors',
      'fishing',
      'car',
      'care',
      'lawn',
      'garage',
      'home',
      'tools',
      'snack',
      'chair',
      'cooler',
      'popcorn',
      'cards',
      'poker',
    ],
    "Mother": [
      'flowers',
      'baking',
      'candels',
      'soap',
      'baskets',
      'gardening',
      'decorations',
      'home',
      'pictures',
      'games',
      'novelty',
      'perfume',
      'earrings',
      'necklace',
      'jewlery',
    ],
    "universal": [
      'board',
      'game',
    ],
    "over18": [],
    "under18": []
  };
}
